services:
  - type: web
    name: telegram-music-bot
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python webhook_server.py"
    envVars:
      - key: RENDER_EXTERNAL_URL
        fromService:
          type: web
          name: telegram-music-bot
          property: url